In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

print(a1)
print(type(a1))
print(a1.shape) #1차원 배열에 3개의 데이터를 가지고 있음

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(type(a2))
print(a2.shape) #2차원 배열 2행 3열

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [7]:
a3 = np.array([[1,2,3]])
print(a3)
print(type(a3))
print(a3.shape) #2차원 배열 1행 3열

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)


In [8]:
print(a1.ndim) #1차원 배열
print(a2.ndim) #2차원 배열
print(a3.ndim) #2차원 배열

1
2
2


In [9]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
print(type(a))
print(a.ndim)
print(a.shape)

<class 'numpy.ndarray'>
1
(20,)


In [11]:
a = np.arange(1,20,3)
print(a)
print(a.ndim)
print(a.shape)

[ 1  4  7 10 13 16 19]
1
(7,)


In [13]:
zero_a = np.zeros((2,5))
print(zero_a)
print(zero_a.ndim)
print(zero_a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
(2, 5)


In [14]:
ones_a = np.ones((3,4))
print(ones_a)
print(ones_a.ndim)
print(ones_a.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
(3, 4)


In [15]:
zero_b = np.zeros_like(ones_a)
print(zero_b)
print(zero_b.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [16]:
ones_b = np.ones_like(zero_a)
print(ones_b)
print(ones_b.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


In [17]:
full_a = np.full((4,3), 9)
print(full_a)
print(full_a.shape)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
(4, 3)


In [18]:
random_a = np.random.random((3,4))
print(random_a)
print(random_a.shape)

[[0.29391762 0.2044284  0.42850258 0.51320548]
 [0.98973956 0.46500683 0.00223873 0.50729878]
 [0.27519688 0.59095023 0.44885624 0.09089071]]
(3, 4)


In [21]:
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
arr = np.arange(12) # [0 1 2 3 4 5 6 7 8 9 10 11]
arr2 = arr.reshape(3,4) #arr를 3행 4열로 변환
arr3= arr.reshape(3,4, order = 'F') #arr를 3행 4열로 변환하는데 값을 열부터 채워 넣음

print(arr)
print(arr2)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [25]:
arr = np.arange(10)
arr2 = arr.reshape(-1,5)

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
(2, 5)


In [27]:
arr = np.arange(12)
arr2 = arr.reshape(2,3,2, order = 'F')

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
3
(2, 3, 2)


In [28]:
arr2= np.array([[1,2,3],[4,5,6]])
arr = arr2.flatten()
print(arr)

[1 2 3 4 5 6]


In [29]:
array1 = np.arange(1,10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [30]:
print(array1[2])

3


In [31]:
print(array1[-2])

8


In [35]:
array1[0:3]

array([1, 2, 3])

In [32]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
arr[0][0]

1

In [34]:
arr[2][2]

9

In [41]:
lst = [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
lst[0]

[1, 2, 3]

In [46]:
lst[:3][1:]

[[4, 5, 6], [7, 8, 9]]

In [48]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8],
                [9,10],
                [11,12]])
dot_arr = np.dot(arr1, arr2)
print(dot_arr)

[[ 58  64]
 [139 154]]


In [51]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr_t = arr1.T
print(arr_t)

[[1 4]
 [2 5]
 [3 6]]


In [53]:
len(arr_t)

3

In [55]:
arr = np.arange(18)
print(len(arr))

arr2 = arr.reshape(-1,6)
print(len(arr2))
print(arr2.shape)

18
3
(3, 6)


In [56]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))

26
4.8076923076923075
115.23224852071006
10.734628476137871


In [57]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(np.max(x))
print(np.min(x))
print(np.median(x))

23
-24
5.0


In [58]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))

0.0
5.0
10.0
